spring.application.name=mundo-entre-libros

spring.datasource.url=jdbc:mysql://localhost:3306/mundo_entre_libros
spring.datasource.username=root
spring.datasource.password=mago020803

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

